DROP SEQUENCE obra_seq;
DROP SEQUENCE artista_seq;
DROP SEQUENCE lista_watch_seq;
DROP SEQUENCE lista_per_seq;
DROP SEQUENCE usuario_seq;

CREATE SEQUENCE obra_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE artista_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE lista_per_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE lista_watch_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE usuario_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;