CREATE OR REPLACE TRIGGER trg_obra_id
BEFORE INSERT ON Obra
FOR EACH ROW
BEGIN
    SELECT obra_seq.NEXTVAL 
    INTO :NEW.id 
    FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER trg_artista_id
BEFORE INSERT ON Artistas
FOR EACH ROW
BEGIN
    SELECT artista_seq.NEXTVAL 
    INTO :NEW.id 
    FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER trg_lista_id
BEFORE INSERT ON Lista
FOR EACH ROW
BEGIN
    SELECT lista_seq.NEXTVAL 
    INTO :NEW.id 
    FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER trg_usuario_id
BEFORE INSERT ON Usuario
FOR EACH ROW
BEGIN
    SELECT usuario_seq.NEXTVAL 
    INTO :NEW.id 
    FROM DUAL;
END;
/
