CREATE OR REPLACE TRIGGER trg_obra_id
BEFORE INSERT ON Obra
FOR EACH ROW
BEGIN
    SELECT obra_seq.NEXTVAL 
    INTO :NEW.id 
    FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER trg_artista_id
BEFORE INSERT ON Artistas
FOR EACH ROW
BEGIN
    SELECT artista_seq.NEXTVAL 
    INTO :NEW.id 
    FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER trg_lista_per_id
BEFORE INSERT ON Lista_Personalizada
FOR EACH ROW
BEGIN
    SELECT lista_per_seq.NEXTVAL 
    INTO :NEW.id 
    FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER trg_lista_watch_id
BEFORE INSERT ON Watchlist
FOR EACH ROW
BEGIN
    SELECT lista_watch_seq.NEXTVAL 
    INTO :NEW.id 
    FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER trg_usuario_id
BEFORE INSERT ON Usuario
FOR EACH ROW
BEGIN
    SELECT usuario_seq.NEXTVAL 
    INTO :NEW.id 
    FROM DUAL;
END;
/
